=== abdrocket/practica3/src/main/resources/eurovision.dtd
<!ELEMENT eurovision (artista*, edicion*)>
<!ELEMENT artista (nombre, descripcion?, url-img?)>
<!ELEMENT nombre EMPTY>
<!ELEMENT descripcion EMPTY>
<!ELEMENT url-img (#PCDATA)>
<!ELEMENT edicion (anno, ciudad, pais, interpretes-paises)>
<!ELEMENT anno EMPTY>
<!ELEMENT ciudad EMPTY>
<!ELEMENT pais EMPTY>
<!ELEMENT interpretes-paises (interprete-pais)*>
<!ELEMENT interprete-pais (voto)*>
<!ELEMENT voto EMPTY>
<!ATTLIST artista cod-artista ID #REQUIRED>
<!ATTLIST nombre text CDATA #REQUIRED>
<!ATTLIST descripcion text CDATA #REQUIRED>
<!ATTLIST anno text CDATA #REQUIRED>
<!ATTLIST ciudad text CDATA #REQUIRED>
<!ATTLIST pais text CDATA #REQUIRED>
<!ATTLIST interprete-pais artista IDREF #REQUIRED>
<!ATTLIST interprete-pais pais CDATA #REQUIRED>
<!ATTLIST interprete-pais cancion CDATA #REQUIRED>
<!ATTLIST interprete-pais orden CDATA #REQUIRED>
<!ATTLIST voto receptor CDATA #REQUIRED>
<!ATTLIST voto nota CDATA #REQUIRED>

=== abdrocket/practica3/src/main/resources/Eurovision.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eurovision SYSTEM "eurovision.dtd">
<eurovision>
	<artista cod-artista = "a0001">
		<nombre text = "Rodolfo Chikilicuatre"/>
		<descripcion text = "Freak"/>
	</artista>
	<artista cod-artista = "a0002">
		<nombre text = "Tipo random de Finlandia"/>
		<descripcion text = "Freak satanico del norte"/>
	</artista>
	<artista cod-artista = "a0003">
		<nombre text = "Bertin Osborne"/>
		<descripcion text = "Latin lover"/>
	</artista>
	<artista cod-artista = "a0004">
		<nombre text = "Peter Pan"/>
		<descripcion text = "No quiere crecer"/>
	</artista>
	<artista cod-artista = "a0005">
		<nombre text = "Princesa Chicle"/>
		<descripcion text = "Muy dulce"/>
	</artista>
	<artista cod-artista = "a0006">
		<nombre text = "Rey Hielo"/>
		<descripcion text = "No quiere crecer"/>
	</artista>
	<artista cod-artista = "a0007">
		<nombre text = "Princesa bultos"/>
		<descripcion text = "Que te bulten!"/>
	</artista>
	<artista cod-artista = "a0008">
		<nombre text = "Princesa Llama"/>
		<descripcion text = "Paaaaaaaso, que voy ardiendoooo"/>
	</artista>
	<artista cod-artista = "a0009">
		<nombre text = "Asuranceturix"/>
		<descripcion text = "Voz de ruiseñor"/>
	</artista>
	<artista cod-artista = "a0010">
		<nombre text = "El Sevilla"/>
		<descripcion text = "Voz de ruiseñor"/>
	</artista>
	<edicion>
		<anno text = "2008"/>
		<ciudad text = "Belgrado"/>
		<pais text = "Servia"/>
		<interpretes-paises>
			<interprete-pais artista = "a0001" pais = "Spain" cancion = "Baila el Chiki-Chiki" orden = "1">
				<voto receptor = "Nunca Jamas" nota = "9"/>
				<voto receptor = "Galia" nota = "10"/>
			</interprete-pais>
			<interprete-pais artista = "a0002" pais = "Finlandia" cancion = "Satan Satan Satan" orden = "3">
				<voto receptor = "Galia" nota = "7"/>
				<voto receptor = "Spain" nota = "1"/>
			</interprete-pais>
			<interprete-pais artista = "a0003" pais = "Navidul" cancion = "Baladas baladeras" orden = "2">
				<voto receptor = "Finlandia" nota = "6"/>
				<voto receptor = "Spain" nota = "3"/>
			</interprete-pais>
			<interprete-pais artista = "a0004" pais = "Nunca Jamas" cancion = "Los ninios perdidos" orden = "4">
				<voto receptor = "Navidul" nota = "1"/>
				<voto receptor = "Spain" nota = "3"/>
			</interprete-pais>
			<interprete-pais artista = "a0009" pais="Galia" cancion="Rock del Menhir" orden="5">
				<voto receptor="Navidul" nota="1"/>
				<voto receptor="Spain" nota="3"/>
			</interprete-pais>
		</interpretes-paises>
	</edicion>
	<edicion>
		<anno text="2016"/>
		<ciudad text="Ciudad de los Ladrones"/>
		<pais text="Reino de O"/>
		<interpretes-paises>
			<interprete-pais artista = "a0005" pais="Chuchelandia" cancion="Baila el Chiki-Chiki" orden="3">
				<voto receptor="Reino de Fuego" nota="8"/>
				<voto receptor="Spain" nota="2"/>
			</interprete-pais>
			<interprete-pais artista = "a0006" pais="Reino de Hielo" cancion="Satan Satan Satan" orden="2">
				<voto receptor="Reino de Fuego" nota="1"/>
				<voto receptor="Chuchelandia" nota="9"/>
			</interprete-pais>
			<interprete-pais artista = "a0007" pais="Espacio Bultos" cancion="Baladas baladeras" orden="4">
				<voto receptor="Chuchelandia" nota="6"/>
				<voto receptor="Spain" nota="3"/>
			</interprete-pais>
			<interprete-pais artista = "a0008" pais="Reino de Fuego" cancion="Los ninios perdidos" orden="1">
				<voto receptor="Reino de Hielo" nota="1"/>
				<voto receptor="Espacio Bultos" nota="2"/>
			</interprete-pais>
			<interprete-pais artista = "a0010" pais="Spain" cancion="El hombre que era viejo y verde a la ve" orden="5">
				<voto receptor="Chuchelandia" nota="9"/>
				<voto receptor="Reino de Hielo" nota="6"/>
			</interprete-pais>
		</interpretes-paises>
	</edicion>
</eurovision>

=== abdrocket/practica3/target/classes/Eurovision.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eurovision SYSTEM "eurovision.dtd">
<eurovision>
	<artista cod-artista = "a0001">
		<nombre text = "Rodolfo Chikilicuatre"/>
		<descripcion text = "Freak"/>
	</artista>
	<artista cod-artista = "a0002">
		<nombre text = "Tipo random de Finlandia"/>
		<descripcion text = "Freak satanico del norte"/>
	</artista>
	<artista cod-artista = "a0003">
		<nombre text = "Bertin Osborne"/>
		<descripcion text = "Latin lover"/>
	</artista>
	<artista cod-artista = "a0004">
		<nombre text = "Peter Pan"/>
		<descripcion text = "No quiere crecer"/>
	</artista>
	<artista cod-artista = "a0005">
		<nombre text = "Princesa Chicle"/>
		<descripcion text = "Muy dulce"/>
	</artista>
	<artista cod-artista = "a0006">
		<nombre text = "Rey Hielo"/>
		<descripcion text = "No quiere crecer"/>
	</artista>
	<artista cod-artista = "a0007">
		<nombre text = "Princesa bultos"/>
		<descripcion text = "Que te bulten!"/>
	</artista>
	<artista cod-artista = "a0008">
		<nombre text = "Princesa Llama"/>
		<descripcion text = "Paaaaaaaso, que voy ardiendoooo"/>
	</artista>
	<artista cod-artista = "a0009">
		<nombre text = "Asuranceturix"/>
		<descripcion text = "Voz de ruiseñor"/>
	</artista>
	<artista cod-artista = "a0010">
		<nombre text = "El Sevilla"/>
		<descripcion text = "Voz de ruiseñor"/>
	</artista>
	<edicion>
		<anno text = "2008"/>
		<ciudad text = "Belgrado"/>
		<pais text = "Servia"/>
		<interpretes-paises>
			<interprete-pais artista = "a0001" pais = "Spain" cancion = "Baila el Chiki-Chiki" orden = "1">
				<voto emisor = "Nunca Jamas" nota = "9"/>
				<voto emisor = "Galia" nota = "9"/>
				<voto emisor = "Finlandia" nota = "6"/>
			</interprete-pais>
			<interprete-pais artista = "a0002" pais = "Finlandia" cancion = "Satan Satan Satan" orden = "3">
				<voto emisor = "Galia" nota = "7"/>
				<voto emisor = "Nunca Jamas" nota = "8"/>
				<voto emisor = "Spain" nota = "1"/>
			</interprete-pais>
			<interprete-pais artista = "a0003" pais = "Navidul" cancion = "Baladas baladeras" orden = "2">
				<voto emisor = "Finlandia" nota = "2"/>
				<voto emisor = "Spain" nota = "3"/>
				<voto emisor = "Galia" nota = "10"/>
			</interprete-pais>
			<interprete-pais artista = "a0004" pais = "Nunca Jamas" cancion = "Los ninios perdidos" orden = "4">
				<voto emisor = "Navidul" nota = "1"/>
				<voto emisor = "Spain" nota = "4"/>
			</interprete-pais>
			<interprete-pais artista = "a0009" pais="Galia" cancion="Rock del Menhir" orden="5">
				<voto emisor="Navidul" nota="2"/>
				<voto emisor="Spain" nota="5"/>
			</interprete-pais>
		</interpretes-paises>
	</edicion>
	<edicion>
		<anno text="2016"/>
		<ciudad text="Ciudad de los Ladrones"/>
		<pais text="Reino de O"/>
		<interpretes-paises>
			<interprete-pais artista = "a0005" pais="Chuchelandia" cancion="I love candy" orden="3">
				<voto emisor="Reino de Fuego" nota="8"/>
				<voto emisor="Spain" nota="9"/>
			</interprete-pais>
			<interprete-pais artista = "a0006" pais="Reino de Hielo" cancion="Oh, Gunter!" orden="2">
				<voto emisor="Reino de Fuego" nota="1"/>
				<voto emisor="Chuchelandia" nota="9"/>
				<voto emisor="Spain" nota="2"/>
			</interprete-pais>
			<interprete-pais artista = "a0007" pais="Espacio Bultos" cancion="Baladas baladeras" orden="4">
				<voto emisor="Chuchelandia" nota="6"/>
				<voto emisor="Spain" nota="3"/>
			</interprete-pais>
			<interprete-pais artista = "a0008" pais="Reino de Fuego" cancion="Los ninios perdidos" orden="1">
				<voto emisor="Reino de Hielo" nota="1"/>
				<voto emisor="Espacio Bultos" nota="2"/>
			</interprete-pais>
			<interprete-pais artista = "a0010" pais="Spain" cancion="El hombre que era viejo y verde a la ve" orden="5">
				<voto emisor="Chuchelandia" nota="8"/>
				<voto emisor="Reino de Hielo" nota="6"/>
				<voto emisor="Espacio Bultos" nota="3"/>
			</interprete-pais>
		</interpretes-paises>
	</edicion>
</eurovision>
